enyo.depends(
	"views.js",
	"room_screen.js",
	"restaurant_screen.js",
	"foodinfo_screen.js",
	"checkout_screen.js",
	"main_screen.js",
	"mediabrowser_screen.js",
	"checkin_screen.js",
	"explore_screen.js",
	"promotion_screen.js"
);
